In [6]:
#vec

In [5]:
c()

NULL

In [3]:
c  = "nithin"
print(c)

[1] "nithin"


In [9]:
12 -> c

In [10]:
class(c)

[1] "numeric"

In [12]:
c

[1] 12

In [14]:
vec <- c(1,2, 3)

In [18]:
summary(vec)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.5     2.0     2.0     2.5     3.0 

In [19]:
 vd <- 1:100 # range(0, 100), range(1, 100)

In [20]:
vd

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [21]:
nithin.v = "sdf"

In [23]:
nithin.v

[1] "sdf"

In [22]:
is.numeric(c)

[1] TRUE

In [27]:
ts <- as.character(134) # f"{123}" str(123)
class(ts)
print(ts)

[1] "character"

[1] "134"


In [16]:
x <- 12

In [17]:
x

[1] 12

In [24]:
132412 -> x

In [30]:
vd # starting index in python  0, starting index in r is 1 

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [29]:
class(print(class(vd)))

[1] "integer"


[1] "character"

In [35]:
c = seq(1,20, .2) # range(1, 20, 2)

In [36]:
c

[1]  1.0  1.2  1.4  1.6  1.8  2.0  2.2  2.4  2.6  2.8  3.0  3.2  3.4  3.6  3.8
[16]  4.0  4.2  4.4  4.6  4.8  5.0  5.2  5.4  5.6  5.8  6.0  6.2  6.4  6.6  6.8
[31]  7.0  7.2  7.4  7.6  7.8  8.0  8.2  8.4  8.6  8.8  9.0  9.2  9.4  9.6  9.8
[46] 10.0 10.2 10.4 10.6 10.8 11.0 11.2 11.4 11.6 11.8 12.0 12.2 12.4 12.6 12.8
[61] 13.0 13.2 13.4 13.6 13.8 14.0 14.2 14.4 14.6 14.8 15.0 15.2 15.4 15.6 15.8
[76] 16.0 16.2 16.4 16.6 16.8 17.0 17.2 17.4 17.6 17.8 18.0 18.2 18.4 18.6 18.8
[91] 19.0 19.2 19.4 19.6 19.8 20.0

In [34]:
help(seq)

In [37]:
c = 1:20

In [38]:
a <- 2:10

In [39]:
class(c(10:12))

[1] "integer"

In [41]:
a ^ 2 # [ i **2 for i in a ] , a**2 if numpy array 

[1]   4   9  16  25  36  49  64  81 100

In [43]:
a


[1]  2  3  4  5  6  7  8  9 10

In [42]:
a  ^ a

[1]           4          27         256        3125       46656      823543
[7]    16777216   387420489 10000000000

In [ ]:
#1e-10 -> 10 * -10 

In [44]:
mymatrix <- matrix(1:16,
                   nrow =4, ncol = 4)

In [45]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [46]:
class(mymatrix)

[1] "matrix"

In [47]:
mean(1:10)

[1] 5.5

In [50]:
help(apply)

In [51]:
apply(mymatrix, 1, mean)

[1]  7  8  9 10

In [52]:
a


[1]  2  3  4  5  6  7  8  9 10

In [53]:
mean(a)

[1] 6

In [61]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [60]:
mymatrix[3,] # mymatrix 3 row all values

[1]  3  7 11 15

In [136]:
mymatrix[,3]

[1]  9 10 11 12

In [62]:
mymatrix[1,] #, df.iloc[0, :]

[1]  1  5  9 13

In [3]:
vec<-c(1:10)
length(vec)
vec[1]
vec
vec*2
vec+10



[1] 10

[1]  1  2  3  4  5  6  7  8  9 10

[1] 1

[1]  1  2  3  4  5  6  7  8  9 10

[1]  2  4  6  8 10 12 14 16 18 20

[1] 11 12 13 14 15 16 17 18 19 20

[1]  2  4  6  8 10 12 14 16 18 20

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE

In [63]:
vec2<-c(1:10)
vec+vec2

Warning message in vec + vec2:
“longer object length is not a multiple of shorter object length”

[1]  2  4  6  5  7  9  8 10 12 11

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

In [105]:
vec <= 4 # df.a > 4
vec[vec <= 4]

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

[1] 1 2 3 4

In [79]:
vec<=2
vec[vec<=2]

[1]  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

[1] 1 2

In [80]:

vec <- 1:10
print(vec)

 [1]  1  2  3  4  5  6  7  8  9 10


In [87]:
help(matrix)

In [91]:
matrix(1:10,nrow = 2, ncol = 5, ) # will 

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [76]:
matrix(vec,nrow=2,ncol=5)
matrix(vec,nrow=2,ncol=5,byrow = FALSE)
matrix(1:8,nrow=8,ncol=1,byrow = TRUE)
mata<-matrix(1:8,nrow=2,ncol=4)

Warning message in matrix(vec, nrow = 2, ncol = 5):
“data length [3] is not a sub-multiple or multiple of the number of rows [2]”

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    1    3   
[2,] 2    1    3    2    1

Warning message in matrix(vec, nrow = 2, ncol = 5, byrow = TRUE):
“data length [3] is not a sub-multiple or multiple of the number of rows [2]”

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    1    2   
[2,] 3    1    2    3    1

Warning message in matrix(vec, nrow = 2, ncol = 5, byrow = FALSE):
“data length [3] is not a sub-multiple or multiple of the number of rows [2]”

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    1    3   
[2,] 2    1    3    2    1

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6   
[7,] 7   
[8,] 8

In [5]:
vec

[1]  1  2  3  4  5  6  7  8  9 10

In [9]:
mata

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [10]:
apply(mata, 2, sum)

[1]  3  7 11 15

In [11]:
apply(mata, 1, sum)

[1] 16 20

In [94]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [95]:
df <- data.frame(mymatrix)

In [96]:
df

X1 X2 X3 X4
1 1  5   9 13
2 2  6  10 14
3 3  7  11 15
4 4  8  12 16

In [100]:
df$X4 # df.X4 , df["X4"]

[1] 13 14 15 16

In [50]:
df$X2

[1] 5 6 7 8

In [107]:
help(sapply)

In [52]:
sapply(df , sum)

X1 X2 X3 X4 
10 26 42 58

In [108]:
summary(df)

       X1             X2             X3              X4       
 Min.   :1.00   Min.   :5.00   Min.   : 9.00   Min.   :13.00  
 1st Qu.:1.75   1st Qu.:5.75   1st Qu.: 9.75   1st Qu.:13.75  
 Median :2.50   Median :6.50   Median :10.50   Median :14.50  
 Mean   :2.50   Mean   :6.50   Mean   :10.50   Mean   :14.50  
 3rd Qu.:3.25   3rd Qu.:7.25   3rd Qu.:11.25   3rd Qu.:15.25  
 Max.   :4.00   Max.   :8.00   Max.   :12.00   Max.   :16.00  

In [113]:
## Writing a function 

tfunc <- function(a){
    v <- 1 : 10
    return(v + a)
}

# def tfunc(a):
#     return [v + a for v in range(1, 11)] 


tfunc(10)

[1] 11 12 13 14 15 16 17 18 19 20

In [115]:
t_vec <- tfunc(1)
t_vec

[1]  2  3  4  5  6  7  8  9 10 11

In [116]:
length(t_vec)

[1] 10

In [118]:
avg <- function(x){
    return(sum(x)/length(x))
}

In [119]:
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [123]:
apply(mymatrix, 1, avg)

[1]  7  8  9 10

In [125]:
new <- sapply(df, avg)

In [133]:
new["X1"]


X1 
2.5

In [135]:

summary(t_vec)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2.00    4.25    6.50    6.50    8.75   11.00 

In [ ]:
# wirte function to check if number is prime ?
# find 111111 prime number?
# In R if possible in python